In [1]:
import numpy as np

In [2]:
a=[2,3,4,5,6]
b=[2,5,8,5,3]

In [3]:
#1.1.
c= a+b
print(f"sum of list {a} and {b} is {c}")

sum of list [2, 3, 4, 5, 6] and [2, 5, 8, 5, 3] is [2, 3, 4, 5, 6, 2, 5, 8, 5, 3]


In [4]:
#1.2
A= np.array(a)
B= np.array(b)

In [5]:
A

array([2, 3, 4, 5, 6])

In [6]:
#1.3
c=A*B
print(f"multiplication of {a} and {b} is {c}")

d= np.array(A)**np.array(B)
print(f"power of array(A) is np.array(B) the answer is {d}")

multiplication of [2, 3, 4, 5, 6] and [2, 5, 8, 5, 3] is [ 4 15 32 25 18]
power of array(A) is np.array(B) the answer is [    4   243 65536  3125   216]


In [7]:
#2. dimension of arrays
s= np.array(45).ndim
print(f"2.1 dimension of s Array is {s}")
d= np.array([42, 34, 45]).ndim
print(f"2.2 dimension of d  Array is {d}")
f= np.array([[[1, 2, 3],[4, 5, 6]],[[1, 2, 3],[3, 4, 5]]]).ndim
print(f"2.3 dimension of f Array is {f}")
g= np.array([[[[[1, 2, 3, 4, 5, 6], [2, 3, 4, 5, 6, 7]]]]]).ndim
print(f"2.4 dimension of g Array is {g}")


2.1 dimension of s Array is 0
2.2 dimension of d  Array is 1
2.3 dimension of f Array is 3
2.4 dimension of g Array is 5


In [8]:
#4.
perm= np.array([[13,23,32,43,54],[43,55,60,7,8],[12,34,45,77,87],[2,55,39,82,49]])

In [9]:
perm

array([[13, 23, 32, 43, 54],
       [43, 55, 60,  7,  8],
       [12, 34, 45, 77, 87],
       [ 2, 55, 39, 82, 49]])

In [10]:
perm[1:3]

array([[43, 55, 60,  7,  8],
       [12, 34, 45, 77, 87]])

In [11]:
perm[1:3,2:4]

array([[60,  7],
       [45, 77]])

In [12]:
k = np.random.normal(loc = 7,scale = 3,size = 1000)

In [13]:
k

array([ 4.94954468,  6.27299229,  7.35344346,  3.17883336,  6.54077706,
        8.33298824,  8.37081636, 10.62913667,  9.08414015,  7.5009597 ,
        6.71582897,  5.08073418,  6.40738945,  6.30201918,  3.96445269,
        7.01716432, 13.67216387, 12.2879507 ,  9.28179397,  2.06863978,
        6.75598192, 11.39022177,  3.00381999,  8.26734778,  8.2410137 ,
        5.60513628,  3.03206881,  6.3455534 ,  4.4645072 ,  8.63644872,
        8.33402482,  3.63872446, 12.08472205,  6.14355311,  6.0395498 ,
        6.53914549,  3.56227089,  9.14375783,  7.45022451,  5.01659586,
        1.87849864,  6.69992435,  8.72153399,  9.44576407,  6.53768987,
        2.83981771,  4.02826502,  9.13426335,  5.91158871,  6.62182261,
        9.5976771 ,  3.06345871,  4.93134796, 12.83047036,  3.87063542,
        8.15543313, 11.09058716, 16.43375347,  1.94131019,  6.60203086,
        5.9239297 ,  8.08722856,  7.93309021, 11.49467842,  2.03205451,
       10.23042149,  7.08379828,  8.40869988,  7.40399622,  9.80

In [14]:
len(k)

1000

In [15]:
l= np.random.uniform(20,30,100)

In [16]:
l

array([28.24319333, 24.72323275, 22.0732066 , 24.33358283, 26.92832419,
       27.04324891, 22.88078989, 24.93519503, 23.3575663 , 23.68670435,
       28.04960294, 22.59300295, 22.8510828 , 29.53489298, 25.21767529,
       23.80563961, 26.05513448, 26.104326  , 28.40020678, 29.51007237,
       29.74465929, 26.0017494 , 27.34219468, 27.70116971, 26.83491362,
       23.63799843, 26.55909483, 29.04573508, 20.94923162, 29.64822824,
       21.6013495 , 28.00282471, 21.38591446, 25.27474567, 27.23723961,
       25.46935046, 29.00537676, 21.4104794 , 27.61249101, 23.33062182,
       26.13740146, 23.65698722, 21.04242692, 25.19403554, 20.80217712,
       21.66407812, 20.48687225, 25.94411348, 25.12334147, 26.90693308,
       22.52694471, 22.46421606, 24.90300593, 25.46023093, 29.23817445,
       22.2705156 , 26.73842113, 25.96860562, 22.46608605, 26.77760405,
       20.29180981, 23.71023561, 29.07652853, 24.62596289, 21.21680837,
       21.76581799, 27.99786476, 26.61865264, 21.22663795, 20.79

In [17]:
len(l)

100

In [79]:
m= np.random.rand(1000)

In [81]:
m

array([7.12769583e-01, 5.09172053e-01, 2.16507426e-01, 2.90693229e-01,
       5.36874633e-01, 3.78719108e-01, 7.00652159e-01, 3.21337053e-01,
       2.62903417e-01, 7.57046799e-01, 1.37304971e-01, 9.88639957e-01,
       6.78621456e-01, 7.50591549e-01, 5.81038660e-01, 9.03067213e-01,
       8.02188318e-01, 4.07715685e-01, 1.44373576e-01, 2.45438413e-02,
       9.25296155e-02, 4.09552241e-01, 2.61443808e-02, 1.07523580e-01,
       6.56868277e-01, 5.72907382e-01, 4.73398030e-01, 7.38553827e-01,
       1.91215143e-01, 7.08571749e-01, 4.61791106e-01, 9.95164431e-01,
       4.00113692e-01, 2.94839371e-01, 6.23218055e-01, 8.50926299e-01,
       9.70668400e-01, 5.75523389e-01, 7.68732124e-01, 6.63133410e-01,
       1.04030519e-01, 9.32615370e-01, 2.47834468e-01, 2.23278812e-01,
       9.29341945e-01, 1.26612963e-02, 2.49737646e-01, 1.06430769e-01,
       3.50742483e-01, 1.45137737e-01, 6.90766448e-01, 1.83659718e-01,
       3.32923022e-01, 7.78011874e-01, 4.38044794e-01, 3.02154387e-01,
      

In [83]:
len(m)

1000

In [85]:
np.round(m,2)

array([0.71, 0.51, 0.22, 0.29, 0.54, 0.38, 0.7 , 0.32, 0.26, 0.76, 0.14,
       0.99, 0.68, 0.75, 0.58, 0.9 , 0.8 , 0.41, 0.14, 0.02, 0.09, 0.41,
       0.03, 0.11, 0.66, 0.57, 0.47, 0.74, 0.19, 0.71, 0.46, 1.  , 0.4 ,
       0.29, 0.62, 0.85, 0.97, 0.58, 0.77, 0.66, 0.1 , 0.93, 0.25, 0.22,
       0.93, 0.01, 0.25, 0.11, 0.35, 0.15, 0.69, 0.18, 0.33, 0.78, 0.44,
       0.3 , 0.11, 0.43, 0.15, 0.94, 0.14, 0.53, 0.42, 0.39, 0.59, 0.4 ,
       0.39, 0.12, 0.94, 0.52, 0.35, 0.98, 0.42, 0.09, 0.81, 0.36, 0.54,
       0.94, 0.01, 0.36, 0.49, 0.08, 0.84, 0.18, 0.57, 0.14, 0.55, 0.19,
       0.36, 0.49, 0.95, 0.56, 0.09, 0.65, 0.02, 0.21, 0.1 , 0.25, 0.91,
       0.34, 0.39, 0.25, 0.73, 0.65, 0.44, 0.16, 0.07, 0.57, 0.13, 0.82,
       0.73, 0.7 , 0.88, 0.4 , 0.2 , 0.95, 0.06, 0.26, 0.25, 0.25, 0.67,
       0.53, 0.24, 0.29, 0.12, 0.02, 0.67, 0.88, 0.94, 0.73, 0.53, 0.8 ,
       0.83, 0.82, 0.55, 0.95, 0.76, 0.31, 0.42, 0.32, 0.79, 0.39, 0.78,
       0.45, 0.15, 0.84, 0.52, 0.37, 0.59, 0.56, 0.

In [87]:
len(m)

1000